#!/bin/sh

set -e

# Install
pip install -e .

# Cleanup
pip cache purge
conda clean -afy
rm -rf /tmp/* ~/.cache
find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null
apt-get clean && rm -rf /var/lib/apt/lists/*
